import { jsPDF } from 'jspdf'

export const generatePDFReport = (calculationType, inputs, results) => {
  const doc = new jsPDF()
  
  // Add Arabic font support (this would need proper Arabic font)
  doc.setFont('helvetica')
  doc.setFontSize(16)
  
  // Header
  doc.text('Engineering Calculator Report', 20, 20)
  doc.text('تقرير الحاسبة الهندسية', 20, 30)
  
  // Date
  const date = new Date().toLocaleDateString('ar-EG')
  doc.setFontSize(12)
  doc.text(`Date / التاريخ: ${date}`, 20, 50)
  
  // Calculation Type
  doc.text(`Calculation Type / نوع الحساب: ${calculationType}`, 20, 70)
  
  // Inputs
  doc.text('Inputs / المدخلات:', 20, 90)
  let yPosition = 100
  
  Object.entries(inputs).forEach(([key, value]) => {
    doc.text(`${key}: ${value}`, 30, yPosition)
    yPosition += 10
  })
  
  // Results
  yPosition += 10
  doc.text('Results / النتائج:', 20, yPosition)
  yPosition += 10
  
  Object.entries(results).forEach(([key, value]) => {
    if (value && typeof value === 'string') {
      doc.text(value, 30, yPosition)
      yPosition += 10
    }
  })
  
  // Footer
  doc.text('Generated by All-in-One Engineering Calculator', 20, 280)
  doc.text('تم إنشاؤه بواسطة الحاسبة الهندسية الشاملة', 20, 290)
  
  // Save the PDF
  doc.save(`engineering-report-${Date.now()}.pdf`)
}

export default generatePDFReport

